### ISSUE TITLE
can't install madmom

### ISSUE THREAD

**Issue by expungedthefunniguy** [CPJKU/madmom#528]
### Expected behaviour

to install

### Actual behaviour

this
C:\Users\(My Username)>pip install --user madmom
Collecting madmom
  Using cached madmom-0.16.1.tar.gz (20.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\(My Username)\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\(My Username)\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\(My Username)\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\(My Username)\AppData\Local\Temp\pip-build-env-myh8j06p\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\(My Username)\AppData\Local\Temp\pip-build-env-myh8j06p\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\(My Username)\AppData\Local\Temp\pip-build-env-myh8j06p\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\(My Username)\AppData\Local\Temp\pip-build-env-myh8j06p\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Steps needed to reproduce the behaviour

i would say
pip install madmom
but that won't really reproduce it

### Information about installed software

i already have cython installed so... yeah. i have no idea what the problem could be.

**Comment by expungedthefunniguy** [comment]
nevermind i think it's my problem

**Comment by expungedthefunniguy** [comment]
fuck it wasn't

**Comment by th1nhhdk** [comment]
I have the same problem

**Comment by th1nhhdk** [comment]
Fixed it with `pip install git+https://github.com/CPJKU/madmom`

**Comment by Kare-Udon** [comment]
You can install from the source code, it works fine.

**Comment by fluid46** [comment]
Marked completed incorrectly, problem still occurs

**Comment by hitosajishiawa** [comment]
I come across this problem too. I used the script `pip install madmom` and it throw the same error. It is hard to believe that two years later this bug still exists :(
